---
load: POSTWORLD
main: LuckyBlock\Main
name: LuckyBlock
api: [3.0.0-ALPHA4, 3.0.0-ALPHA5]
author: xionbig
version: 4.0.0
website: "https://github.com/xionbig/LuckyBlock"
permissions:
  luckyblock:
    default: false
    description: "Allows using everything LuckyBlock has"
    children:
      luckyblock.command:
        default: op
        description: "Allows using /luckyblock command"
      luckyblock.use:
        default: true
        description: "Allows the player to use the plugin"