---
lucky_block: 19
items_dropped:
- tnt
- "259"
- "17:1"
max_chest_item: 4
explosion_min: 1
explosion_max: 3
status: "on"
level:
- can
- nether
max_duration: 20
functions:
  spawnTree: false
  explosion: false
  dropItem: true
  bedrock: true
  prison: true
  chest: false
  teleport: true
  potion: true
  mob: true
  execCmd: false
  lightning: false
mob:
- Cow
- Pig
mob_explosion_delay: 1
commands:
- kick %PLAYER% You aren't Lucky!
- banip %IP%
potions:
- poison
- slowless
sponge_spawn_chance: 1
...
